{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-utilities-admin.fullname" . }}
  labels:
    {{- include "url-utilities-admin.labels" . | nindent 4 }}
type: Opaque
stringData:
  CORE_API_KEY: {{ required "secrets.CORE_API_KEY is required when secrets.existingSecret is empty" .Values.secrets.CORE_API_KEY | quote }}
{{- end }}
